### PR TITLE
Fix #17: Make the gem compatible with Cloudflare v3 gem

### LINKED ISSUE #17: CloudFlare cache invalidation is broken
This commit https://github.com/leighmcculloch/middleman-cdn/commit/6ecd16d739f0ac73555c05f776399641b6a967d9 introduced a compatibility issue with CloudFlare gem. The gem's API has been changed and the correct connection call now looks like this (see the gem's [docs](https://github.com/ioquatix/cloudflare#usage)):

```ruby
connection = Cloudflare.connect(key: key, email: email)
```

The specs passed because the old `Cloudflare::connection` method is mocked in rspec.

But in reality the `middleman-cdn` gem is not working at all because of this issue.

### PR DESCRIPTION
**Pull request by mkalygin**
This PR fixes #17. But it requires new version of the `cloudflare` gem which is not released yet, because `purge_cache` method is missing in the new version of the `cloudflare` gem. See https://github.com/ioquatix/cloudflare/pull/31 for more info.

I've QA'd it with real API and it worked.

### CODE REVIEW

**Comment by mkalygin** [comment]
@leighmcculloch hopefully the owner of the repo will review it. 🤞

**Comment by mkalygin** [comment]
@leighmcculloch https://github.com/ioquatix/cloudflare/pull/31 has been merged but not released yet. 👍

**Comment by leighmcculloch** [comment]
That's great!!! Thanks for persisting.

**Comment by ioquatix** [comment]
Released in v3.2.0 :) Thanks for your effort.

**Comment by leighmcculloch** [comment]
Woohoo, thanks!

**Comment by mkalygin** [comment]
@leighmcculloch here you go. 💯

**Comment by leighmcculloch** [comment]
Ah, could open a small PR removing that use? Or just reduce ruby support for this gem to that version or greater.

**Comment by mkalygin** [comment]
@leighmcculloch do you mean I need to ask for another release of `cloudflare`? Or should I remove Ruby 2.2 from `middleman-cdn` Travis CI?

**Comment by leighmcculloch** [comment]
@ioquatix ioquatix/cloudflare#31 introduced `&.` into your gem here https://github.com/ioquatix/cloudflare/commit/f7afeda901e07db2baeef5c13a6d5d05e4042b6f#diff-d18eb6fbd551b36132390ab7a15351f2R174, meaning it will only work on ruby2.3+. My gut feeling is that's probably not good for the `cloudflare` gem or `middleman-cdn`, since ruby2.2 isn't that old and still probably commonly used.

Would you be up for releasing a new version of `cloudflare` with the `&.` removed?

**Comment by ioquatix** [comment]
Sure, just make a patch release and add 2.2 to the travis testing matrix, I will merge it.

**Comment by ioquatix** [comment]
Also, 2.2 is EOL, so I'm not bothered either way.

**Comment by mkalygin** [comment]
Awesome, I'll do the patch then. I think that introducing one `&` character is not a good reason to drop 2.2 support lol.

**Comment by leighmcculloch** [comment]
Thanks @mkalygin!

**Comment by mkalygin** [comment]
@leighmcculloch it's green! 🥇

**Comment by leighmcculloch** [comment]
Thanks @mkalygin for bringing the issue to the foreground and making the 3 PRs across both projects to get it fixed! ❤️

**Comment by leighmcculloch** [comment]
This fix has been released in v0.3.1.

**Comment by mkalygin** [comment]
@leighmcculloch NP I'm glad to help you. 😄

**Pull request merged**
